stages:
  load_data:
    cmd: python src/load_save.py --config=config/config.yaml
    deps: 
      - src/load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
    